name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: test (${{ matrix.os }}, node-${{ matrix.node }})
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [18.x, 22.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Check Format
        run: npm run format && git diff --exit-code
      - name: Test
        run: npm test
      - name: Slow Test
        run: npm run test:slow

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        id: release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      release_version: ${{ steps.release.outputs.release_version }}
